name: Hereafter Musical
favicon: null
layout_spectrum: 0.70141512574628
typography_spectrum: 0.36384941660799086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3332032351754606
  lightness: 0.532352690352127
  saturation: 0.33751013060100377
  rhythmicContrast: 0.43652609270066023
purpose: []
